# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(max_length=250)),
                ('saved_date', models.DateField(auto_now_add=True)),
                ('comic_title', models.CharField(default='', max_length=250)),
                ('alt_text', models.CharField(default='', max_length=250)),
                ('viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
